### ISSUE TITLE
Add chosen shipping method as "Customer Provided Note"

### ISSUE THREAD

**Issue by francas** [KonektOU/estonian-shipping-methods-for-woocommerce#14]
Would it be possible to add the chosen terminal as "Customer provided note" when order is made? I am trying to figure out where to place code but having a hard time since it's my first time trying to edit a plugin.
I'm asking because I'd like to use this information in WooCommerce mobile app.

**Comment by RistoNiinemets** [comment]
Directly editing the plugin (any plugin actually) is considered to be really bad code ethics. Once the plugin is updated, your modifications are all gone. Best way would be to use actions and filters to move the data.

You can add this code to your theme functions.php or any other file that is "allowed" for editing. It will show the chosen terminal under Customer notes in the app (or in other REST API requests), but nowhere else.
```php
add_filter( 'woocommerce_rest_prepare_shop_order_object', function ( $response ) {
	$terminal_name = apply_filters( 'wc_estonian_shipping_method_order_terminal_name', '', wc_get_order( $response->data['id'] ) );

	if ( ! empty( $terminal_name ) ) {
		$response->data['customer_note'] .= "\n" . esc_html__( 'Chosen terminal', 'wc-estonian-shipping-methods' ) . ': ' . $terminal_name;
	}

	return $response;
}, 10, 1);

```

**Comment by francas** [comment]
Well the thing is I need that information saved as customer note or order note, so it's not enough to just show in UI. I ended up adding these lines to abstract in show_selected_terminal method:

`$note = $order->get_customer_note();
			if (strpos($note, ' terminal: ') !== false) {
				return;
			}
			$order->set_customer_note($note . " " . $this->title . " terminal: " . $terminal_name);
			$order->save();`

**Comment by RistoNiinemets** [comment]
Just to understand it a bit more, could you explain why do you need this saved under customer note?

**Comment by francas** [comment]
I'm using WC mobile app, so the value needs to be saved somewhere, as the php filters won't work there.

**Comment by RistoNiinemets** [comment]
I specifically wrote the code for the app, so it would show selected terminal there. I also tested it and sure works with the WooCommerce mobile app. 

The app calls for any information from your store via REST API, and the PHP filter I added, modifies the information just before returning it to app.

**Comment by francas** [comment]
Hm, could you show me a screenshot? Maybe I just don't know where to look at. This is how it currently looks like in the app. I can see the "Chosen terminal..." information in the web, but not on mobile app. Note the "Customer note" is the one that I added.

![Screenshot_20191119-171445_WooCommerce](https://user-images.githubusercontent.com/5138520/69159410-88b1bd80-0af0-11ea-89a0-8d94bc4a4d7d.jpg)

**Comment by francas** [comment]
It seems I misunderstood your answer, as you WERE giving the code for the app (but I somehow thought it was for web..). Thanks, it works as expected. I think it would be useful to have this incorporated in the plugin. Feel free to close the issue if not.

**Comment by RistoNiinemets** [comment]
Glad it worked! I will give it a thought to implement it.

Thanks for using the plugin. You can support the plugin by leaving a review on WordPress.org.
