### ISSUE TITLE
SmartPosti ja Omniva menüü ei ole lehe raamides.

### ISSUE THREAD

**Issue by anarki2k4** [KonektOU/estonian-shipping-methods-for-woocommerce#20]
Paigaldasin plugina (Eesti WooCommerce tarnemeetodid) tutikale lehele. Kassa lehel valides tarnemeetodiks pakiautommadi (omniva või smartpost) tuleb dropmenüü, mis ulatub väljapoole lehekülge ja rikub lehe välimuse ära. Smartposti kulleriga seda probleemi ei ole.

Kasutan Astra teemat. Valides lehe laiuseks boxed või full width ei muutu midagi.

saidi aadress: https://test2.pahklid.ee/

**Comment by RistoNiinemets** [comment]
Tere,

Probleem on kujunduses. Kõige lihtsam ja robustsem parandus oleks, kui lisaksite Custom CSS:
`.woocommerce-checkout-review-order-table select { width: 100%; }`

Tõenäoliselt kuskilt Astra seadetest saab seda teha.
