### ISSUE TITLE
Feature recommendation - to display "0" values when the shipping is free

### ISSUE THREAD

**Issue by valdekseeder** [KonektOU/estonian-shipping-methods-for-woocommerce#22]
Great plugin, but when accordingly to the settings the shipping is free - it doesn't show under the price any value. Such behavior is somewhat confusing towards the customer and I like to recommend - it must show "0" as a shipping cost when the shipping is free :).

**Comment by RistoNiinemets** [comment]
It's actually a behavior of WooCommerce not this plugin.
