### ISSUE TITLE
'wpo_wcpdf_after_order_data' 

### ISSUE THREAD

**Issue by indrektamming** [KonektOU/estonian-shipping-methods-for-woocommerce#23]
I have custom template for "WooCommerce PDF Invoices & Packing Slips" plugin and this action is called:

do_action('wpo_wcpdf_after_order_data', $this->get_type(), $this->order);

The name of the selected terminal does not show up. What can be wrong?

**Comment by RistoNiinemets** [comment]
Hi @indrektamming 

Unfortunately something went wrong with the latest versions of WCPDF. Until fixed in the plugin, you can use this piece of code:

```php
add_action( 'wpo_wcpdf_before_document', function () {
	WC()->shipping();
}, 1, 1 );
```

**Comment by indrektamming** [comment]
Thank you!

Kontakt Risto Niinemets ***@***.***>) kirjutas kuupäeval R,
3. detsember 2021 kell 08:29:
