### ISSUE TITLE
Chosen terminal is not shown on the order in admin

### ISSUE THREAD

**Issue by jooseplall** [KonektOU/estonian-shipping-methods-for-woocommerce#24]
After the purchase there is no chosen terminal name to be seen anywhere in the admin on the order page. 
It is also missing in the thank you page. 

The correct method is shown, but terminal name is missing. 

Tried both with Omniva Parcel machines and Itella. 

Woocommerce version 5.9.0

**Comment by vahem2lu** [comment]
Same here.

Also choosing terminal is not mandatory, which should be.

**Comment by RistoNiinemets** [comment]
I've checked with the latest WordPress and WooCommerce. The terminal is shown and it is required to select it.
It may be a conflict between some other plugins?
