### ISSUE TITLE
Checkout page layout problems

### ISSUE THREAD

**Issue by ijhgnsj** [KonektOU/estonian-shipping-methods-for-woocommerce#26]
<img width="1280" alt="Screenshot 2022-04-14 at 01 09 03" src="https://user-images.githubusercontent.com/103622464/163314688-7c846027-01d9-414f-8be9-9f61a4bd761e.png">

The checkout page layout goes outside of the margins of the website. Is there any way to solve this?

**Comment by RistoNiinemets** [comment]
Duplicate of https://github.com/KonektOU/estonian-shipping-methods-for-woocommerce/issues/20
