### ISSUE TITLE
Parcel machine's list layout is off

### ISSUE THREAD

**Issue by marumaruou** [KonektOU/estonian-shipping-methods-for-woocommerce#27]
Hi! Just downloaded your plugin and added it to my homepage, everything looks good besides that when it comes to choosing parcel machine then the layout is off.  When I choose between different parcel machines then the layout also changes  but would be nice if the selection would fit to frame.  What can I do to fix this problem?
![image](https://user-images.githubusercontent.com/121312805/209391512-52d8df52-0e41-410e-b98e-959b181dc398.png)
![image](https://user-images.githubusercontent.com/121312805/209391537-4488ecb8-185f-4b3a-87c7-3c5fe4fbd2e4.png)
![image](https://user-images.githubusercontent.com/121312805/209391562-ae13f732-efd9-4a6b-aa61-ba1fba60d53c.png)

**Comment by tjuris** [comment]
You could try setting _max-width: 100%;_ CSS to that table that is out of bounds.

**Comment by RistoNiinemets** [comment]
Have a look at issue #20.

**Comment by marumaruou** [comment]
> Have a look at issue #20.

Wonderful! Worked like a charm! Thanks for quick fix.
