### ISSUE TITLE
Smartpost Eesti not working, also Omniva Eesti

### ISSUE THREAD

**Issue by mehha** [KonektOU/estonian-shipping-methods-for-woocommerce#6]
I get following error: Warning: Invalid argument supplied for foreach() in /www/data04/users/m/mehha.planet.ee/htdocs/wp-content/plugins/estonian-shipping-methods-for-woocommerce/includes/abstracts/class-wc-estonian-shipping-method-smartpost.php on line 130 Warning: Invalid argument supplied for foreach() in /www/data04/users/m/mehha.planet.ee/htdocs/wp-content/plugins/estonian-shipping-methods-for-woocommerce/includes/abstracts/class-wc-estonian-shipping-method-smartpost.php on line 130

**Comment by RistoNiinemets** [comment]
Hello,

For some reason, it seems that terminals are not fetched from the external URLs. Only reason I can think of right now, is that your server setting `allow_url_fopen ` is off and therefore does not allow `file_get_contents` function to fetch from external sources.

**Comment by mehist** [comment]
Yep, same problem here as 1/2 cpanel based hosts dont allow _allow_url_fopen_. I traded the file_get_contents command for curl, which is recommended instead and works like a charm.

In _abstracts/class-wc-estonian-shipping-method-omniva.php_ line 58:
```
		//$terminals_json  = file_get_contents( $this->terminals_url );
		
			$ch = curl_init();
			curl_setopt ($ch, CURLOPT_URL, $this->terminals_url);
			curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
			$terminals_json = curl_exec($ch);
			curl_close($ch);
```

and in _abstracts/class-wc-estonian-shipping-method-omniva.php_ line 93:

```
			//$terminals_xml   = @file_get_contents( $this->get_terminals_url() );
			
			$ch = curl_init();
			curl_setopt ($ch, CURLOPT_URL, $this->get_terminals_url());
			curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
			$terminals_xml = curl_exec($ch);
			curl_close($ch);
```

**Comment by mehist** [comment]
Now to think about it, would you mind adding a backup-resort for this issue? I mean via:

```
if (ini_get("allow_url_fopen") ==1) {
$terminals_xml   = @file_get_contents( $this->get_terminals_url() );
 } else {
			$ch = curl_init();
			curl_setopt ($ch, CURLOPT_URL, $this->get_terminals_url());
			curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
			$terminals_xml = curl_exec($ch);
			curl_close($ch);
}
```

That would probably take care of this issue for good (for now...) and i'd sleep more comfortably knowing an update would not break things for me :)


Awesome plugin, btw!

**Comment by mehha** [comment]
Yes its working now and yes its awesome plugin!

**Comment by RistoNiinemets** [comment]
Thanks for that @mehist. I will change it as soon as possible throughout the plugin.

**Comment by RistoNiinemets** [comment]
I just pushed an updated version of the plugin to this repository. @mehha & @mehist, could you download and test it if it works for you?

I switched from all `file_get_contents` usage to `wp_remote_post` (uses cURL) which is surely more reliable.

**Comment by alf127** [comment]
Hey,

Seems like I got a similar problem but without an error code. 
Suddenly there was no option to pick both Omniva and SmartPOST package terminals destinations. 

Will try to update to the new version in repository.

**Comment by alf127** [comment]
The fix worked for me.

Thanks!

**Comment by mehha** [comment]
Omniva and Smartpost working but looks like DPD is not.
Error: Warning: fopen(): ftp:// wrapper is disabled in the server configuration by allow_url_fopen=....
