### ISSUE TITLE
Problems Enabling Shipping methods

### ISSUE THREAD

**Issue by lexxful** [KonektOU/estonian-shipping-methods-for-woocommerce#8]
Hello.
I have problems. I can't enable new shipping methods for my shop.
I've installed and activated plugin "Estonian Shipping Methods for WooCommerce", 
I've enabled methods "Omniva Estonia", "Omniva Latvia", "Omniva Lithuania". (Other methods have the same issue/problem)

But I have no changes, these methods don't show in front-end, and they don't show on **Shipping zones -> Add method**.

![add shipping method](https://user-images.githubusercontent.com/12859497/31402309-4a5008ea-adfe-11e7-9414-275d8c1eb5e0.png)

My Wordpress configuration (plugins activated):
Estonian Shipping Methods for WooCommerce 1.5
WooCommerce 3.1.2
WooCommerce Multilingual 4.2.4
WPML Multilingual CMS 3.7.1
Some additional WPML plugins

How can I debug this problem? Where can I look for error or problems on getting new shipping methods?

**Comment by RistoNiinemets** [comment]
Hi!

Could you also make a screenshot of one of the enabled shipping methods?

Shipping Zones are not related to this plugin and shouldn't be available there. Each shipping method (in this plugin) is strictly country specific so it wouldn't make any sense to be configurable through Shipping Zones.

**Comment by lexxful** [comment]
Here is a screenshot. 
![mehod enabled](https://user-images.githubusercontent.com/12859497/31402904-1d21ded2-ae00-11e7-9e1e-9d6f03844433.png)

> Each shipping method (in this plugin) is strictly country specific

You mean there is some geo-country detection?
I am testing from another country (not Latvia, Estonia, Lithuania) - perhaps that is my problem?

**Comment by RistoNiinemets** [comment]
Well, that could be the problem. For example, Omniva Estonia only works if you have selected "Estonia" as your shipping country in checkout (or billing country). Same goes accordingly for other methods.

**Comment by lexxful** [comment]
@RistoNiinemets Thank you very much for the explanation. My mistake - I was expecting new shipping methods to appear before client choose correct billing/shipping country. Everything works fine.
